human-pangenomics/hprc-data-explorer

README.md
Created a Readme file with basic instructions on how to run the development server
=> chore: created README.md (#7)

.github/workflows/run-playwright-tests.yml, e2e/smoke-test.spec.ts, package-lock.json, package.json, playwright.config.ts
- Installed Playwright and added a similar configs to other Explorer configs
- Added Github action to make tests run on each pull request
- Added smoke test to check that `/` redirects to `/raw-sequencing-data`
=> chore: added basic playwright smoke test (#8)

README.md, files/build-annotation-data.py, files/build-assemblies-data.py, files/build-raw-sequencing-files.py, files/buildHelp.py
- Added script to build annotation data as specified in #11 
- Refactored the existing script to remove duplication
- Updated the Readme to reflect this new script
=> feat: added script to build assembly data (#11)

package-lock.json, package.json
Closes #22.
Updated `findable-ui` to latest `v9.1.0`.
=> fix: pages do not load correctly when a tab through its exact url (#22)

package-lock.json, package.json
=> fix: resolve scrolling issue in left-hand filters (#32)

package-lock.json, package.json
=> chore: upgrade findable UI to 15.0.0 (#67)

scripts/set-version.sh
=> fix: append newline before other content in `set-version.sh` (#82)

site-config/hprc-data-explorer/local/index/rawSequencingDataEntityConfig.ts
- Made "File Accession" a default column between "File Size" and "Sample ID" on the "Sequencing Data" entity
=> feat: made file accession column default (#94)

site-config/hprc-data-explorer/local/index/alignmentEntityConfig.ts
=> feat: remove use case column and filter (#101)

site-config/hprc-data-explorer/category.ts, site-config/hprc-data-explorer/local/index/alignmentEntityConfig.ts
=> feat: adjust alignment filename and version columns (#110)

e2e/testFunctions.ts, next.config.mjs, package-lock.json, package.json
=> chore: update findable-ui to latest v22.0.0 (#114)

site-config/hprc-data-explorer/local/index/annotationEntityConfig.ts
=> feat: remove reference from annotations list (#116)

app/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenuItems/components/LabelIconMenuItem/labelIconMenuItem.styles.ts, app/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenuItems/components/LabelIconMenuItem/labelIconMenuItem.tsx, app/components/index.ts, site-config/hprc-data-explorer/local/config.ts
This pull request introduces a new `LabelIconMenuItem` component and integrates it into the navigation menu, along with a configuration update to include a link to the HPRC website. Below is a summary of the most important changes:
* **Component Implementation**: Added a new `LabelIconMenuItem` React component that displays a label alongside an icon. The component is customizable via props for the icon type, icon font size, and label text. (`labelIconMenuItem.tsx`, [app/components/Layout/components/Header/components/Content/components/Navigation/components/NavigationMenuItems/components/LabelIconMenuItem/labelIconMenuItem.tsxR1-R22](diffhunk://#diff-65b0c07b9d3a07f58b1a5ae4017e075d144422a9f036fc9f1c1e0940f91e5f02R1-R22))
* **Styling**: Created a new `labelIconMenuItem.styles.ts` file to …
=> feat: added link to HPRC #149

catalog/build/py/generated_schema/sequencing_data.py, catalog/build/ts/build-catalog.ts, catalog/schema/generated/schema.ts, catalog/schema/sequencing_data.yaml
Closes #147
I've added all the used instrument model values to the schema while keeping the existing ones, which means we now have `Sequel II` in addition to `PacBio Sequel II` -- might be that we want to only keep one of them?
Other changes are using the name `converage_over_100kb` and adding platform to Illumina
=> feat: update sequencing data schema and rebuild (#147)

catalog/build/py/generated_schema/alignments.py, catalog/build/py/generated_schema/annotations.py, catalog/build/py/generated_schema/assemblies.py, catalog/build/py/generated_schema/sequencing_data.py, catalog/schema/scripts/gen-schema.sh
=> feat: allow extra fields when validating catalog source (#155)

site-config/hprc-data-explorer/local/index/rawSequencingDataEntityConfig.ts
=> feat: remove sequencing data by deepconsensus version chart (#159)

catalog/build/py/generated_schema/sequencing_data.py, catalog/schema/sequencing_data.yaml
Closes #172
- Added basecaller fields to Illumina and Kinnex sequencing data schemas
- Built catalog
=> feat: update schema and catalog following 2025-05-09 review (#172)

site-config/hprc-data-explorer/local/config.ts
=> docs: added documentation links #165

cgl-data.humanpangenome.org
This pull request adds a new deployment script to the `cgl-data.humanpangenome.org` repository. The script automates the build and deployment process for the project.
=> feat: add prod build script (#179)

app/config/config.ts, cgl-data.humanpangenome.org, package.json, site-config/hprc-data-explorer/prod/.env, site-config/hprc-data-explorer/prod/config.ts
=> feat: added prod config #178

app/components/Table/components/TableCell/components/TypographyNoWrap/constants.ts, app/components/Table/components/TableCell/components/TypographyNoWrap/typographyNoWrap.tsx, e2e/testFunctions.ts, next.config.mjs, package-lock.json, package.json, site-config/hprc-data-explorer/local/config.ts, site-config/hprc-data-explorer/local/index/alignment/ui/entityList.ts, site-config/hprc-data-explorer/local/index/alignmentEntityConfig.ts, site-config/hprc-data-explorer/local/index/annotationEntityConfig.ts, site-config/hprc-data-explorer/local/index/assemblyEntityConfig.ts, site-config/hprc-data-explorer/local/index/rawSequencingDataEntityConfig.ts
Closes #188.
This pull request includes updates to improve UI consistency, refactor entity configurations, and enhance dependency management. The most significant changes involve the addition of pinned columns and hiding functionality in entity configurations, refactoring the `TypographyNoWrap` component for better readability, and updating dependencies to their latest versions.
* Added `meta: { columnPinned: true }` to several entity configurations (`annotationEntityConfig`, `alignmentEntityConfig`, `assemblyEntityConfig`, `rawSequencingDataEntityConfig`) to support pinned columns in the UI. [[1]](diffhunk://#diff-dee479e10676f0f4b4d608af63cd6eff3034a2d8f1d3f2373fe32c54439f9822R83) [[2]](diffhunk://#diff-44ed41c32147e3a1bfd26b92d3427055de6a910c308f037223d67a46b2783291R87) …
=> chore: update findable-ui to latest version 38.1.1 (#188)
